name: attendance_tracker
description: A simple attendance debt tracking app
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4
  dio_http2_adapter: ^2.3.1+1
  envied: ^0.5.1
  firebase_analytics: ^10.6.3
  firebase_core: ^2.21.0
  firebase_crashlytics: ^3.4.3
  firebase_performance: ^0.9.3+3
  firebase_performance_dio: ^0.6.0
  flutter_native_splash: ^2.3.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.1.0
  json_serializable: ^6.7.1
  package_info_plus: ^4.2.0
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  envied_generator: ^0.5.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "FFFFFF"
  image: assets/splash/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
